name: Build and Deploy to AKS

on:
  push:
    branches:
      - main

env:
  ACR_NAME: saiacr12345
  IMAGE_NAME: myapp
  RESOURCE_GROUP: Akscluster_group
  AKS_CLUSTER: akscluster

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: |
          {
            "clientId":"${{ secrets.AZURE_CLIENT_ID }}",
            "clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}",
            "subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}",
            "tenantId":"${{ secrets.AZURE_TENANT_ID }}"
          }

    - name: Login to ACR
      run: az acr login --name $ACR_NAME

    - name: Build Docker Image
      run: |
        docker build -t $ACR_NAME.azurecr.io/$IMAGE_NAME:${{ github.sha }} .

    - name: Push Docker Image
      run: |
        docker push $ACR_NAME.azurecr.io/$IMAGE_NAME:${{ github.sha }}

    - name: Get AKS Credentials
      run: |
        az aks get-credentials --resource-group $RESOURCE_GROUP --name $AKS_CLUSTER --overwrite-existing

    - name: Deploy to AKS
      run: |
        kubectl create deployment flask-app --image=$ACR_NAME.azurecr.io/$IMAGE_NAME:${{ github.sha }} --dry-run=client -o yaml | kubectl apply -f -
        kubectl expose deployment flask-app --type=LoadBalancer --port=80 --target-port=5000 --dry-run=client -o yaml | kubectl apply -f -